baseURL: "https://www.benconstable.dev"
title: "Ben Constable | Personal Blog"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  #env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Ben Constable"
  description: "Azure Data & AI Consultant."
  keywords: [Blog]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Ben Constable | Data & AI"

  # home-info mode
  homeInfoParams:
    Title: "Heya \U0001F44B"
    Content: "I am Azure Data & AI Consultant working on a variety of projects to help customers move to the cloud. On my personal blog, you will find some useful takeaways from recent projects:"

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/ben-constable-b2b87617b/"
    - name: github
      url: "https://github.com/benconstable9"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  menu:
    main:
      - identifier: posts
        name: Posts
        url: /posts/
        weight: 10

      - identifier: about
        name: About
        url: /about/
        weight: 10
